# Generated by Django 5.2.2 on 2025-06-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emailtracker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtracker",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
