# Generated by Django 5.2.2 on 2025-06-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_emailtracker_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailtracker",
            old_name="email_tracker",
            new_name="user",
        ),
    ]
