# Generated by Django 5.2.2 on 2025-06-06 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useduuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=0, default=0, max_digits=3),
                ),
                ("text", models.TextField(blank=True)),
                ("title", models.TextField(default="Blank Title")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("video_url", models.URLField()),
                ("audio_url", models.URLField()),
                ("ass_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
