# Generated by Django 5.2.2 on 2025-06-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makevideo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="thumbnail_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
