# Generated by Django 5.2.2 on 2025-06-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makevideo", "0002_taskmodel_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="bg_video_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="speed",
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="voice",
            field=models.CharField(default="af_heart", max_length=100),
        ),
    ]
