# Generated by Django 5.2.2 on 2025-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makevideo", "0003_taskmodel_bg_video_url_taskmodel_speed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackGroundModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="VoiceModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voice", models.CharField(max_length=100)),
            ],
        ),
    ]
