# Generated by Django 5.2.2 on 2025-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makevideo", "0005_voicemodel_voice_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundmodel",
            name="image_url",
            field=models.URLField(default=""),
        ),
    ]
